apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: ajhaa/pingpong:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: PGHOST
              value: postgres-svc
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              value: verysecret