apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: pingpong
          persistentVolumeClaim:
            claimName: uuid-ping-claim
      containers:
        - name: pingpong
          image: ajhaa/pingpong:latest
          env:
            - name: PGHOST
              value: postgres-svc
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              value: verysecret
          volumeMounts: # Mount volume
          - name: pingpong
            mountPath: /app/shared/