apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pingpong-ingress
  namespace: exercises
spec:
  rules:
  - http:
      paths:
      - path: /pingpong/*
        backend:
          serviceName: pingpong
          servicePort: 3000
      - path: /
        backend:
          serviceName: uuid-svc
          servicePort: 3200