apiVersion: v1
kind: Service
metadata:
  name: pingpong
  namespace: exercises

spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - port: 3000
      name: external
      protocol: TCP
      targetPort: 3000