apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todoapp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: todoapp-svc
          servicePort: 2345